config/routes.rb
Rails.application.routes.draw do
  get 'bookings/new'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :teachers, only: [:index, :show, :new, :create]
  resources :teachers do
    resources :vouchers, only: [:new, :create]
    resources :bookings, only: :new
  end

  resources :availabilities do
    resources :timeslots, only: :edit
  end
  resources :timeslots, only: :update
  resources :dashboards, only: :index
  resources :search, only: [:index]
  get "download_homework", to: 'dashboards#download'



  patch 'availabilities_timeslots', to: 'availabilities#update_associated_timeslots', as: "update_associated_timeslots"
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_teacher, only: [:new, :create]
  before_action :set_availabilities, only: [:new, :create]
  # before_action :set_timeslots, only: [:new, :create]

  def new
    # next_day.nil? ? @next_day = @availability : @next_day = next_day
    # previous_day.nil? ? @previous_day = @availability : @previous_day = previous_day
    @booking_json = BookingJsonBuilder.new(@teacher).start
    @vouchers_as_a_student = Voucher.find_by(student_id: current_user.id).counter
  end

  private


  def set_teacher
    @teacher = User.find(params[:teacher_id])
  end

  def set_availabilities
    @availabilities = Availability.where(teacher_id: @teacher.id )
  end

  def set_timeslots
    @timeslots = @availability.timeslots
  end

  def next_day
    # find next day as date object
    Availability.find_by(day: @availability.day + 1.day, teacher_id: @teacher.id)
  end

  def previous_day
    Availability.find_by(day: @availability.day - 1.day, teacher_id: @teacher.id)
  end
end

app/views/bookings/new.html.erb
<div class="container">
    <h4> Please select up to <%= @vouchers_as_a_student %> lessons</h4>
  <div class="booking-page">
    <div class="calendar_card">
      <h5> Select the best day</h5>
      <input type="text" class="datepicker invisible" >
    </div>
    <div class="right_form">
      <h5> Pick the timeslot</h5>
      <div id="selected-timeslot-dates"></div>
    </div>
     <div class="right_form">
      <div class="booking-form form-wrapper" data-availabilities="<%= @availabilities.to_json %>">
        <h5><span id="voucher_count"><%= @vouchers_as_a_student %></span> lessons left to book</h5>
        <%= form_with(url:  update_associated_timeslots_path, method: "patch") do |f| %>
          <%= f.submit "Book now" , class: "btn btn-flat"%>
        <% end %>
      </div>
    </div>
  </div>
</div>



<div id="booking-data" style="display: none;">
  <%= @booking_json %>
</div>