config/routes.rb
Rails.application.routes.draw do
  get 'bookings/new'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :teachers, only: [:index, :show, :new, :create]
  resources :teachers do
    resources :vouchers, only: [:new, :create]
    resources :bookings, only: :new
  end

  resources :availabilities do
    resources :timeslots, only: :edit
  end
  resources :timeslots, only: :update
  resources :dashboards, only: :index
  resources :search, only: [:index]
  get "download_homework", to: 'dashboards#download'



  patch 'availabilities_timeslots', to: 'availabilities#update_associated_timeslots', as: "update_associated_timeslots"
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :create]

  def index
    @teachers = User.where(teacher: true)#.shuffle
    @teachers_geocoded = User.geocoded
    if params[:instrument].present?
      @teachers = @teachers.joins(:instruments).where("name ILIKE ?", "%#{params[:instrument]}%")
    elsif params[:city].present?
      @teachers = @teachers.search_by_address(params[:city])
    else
      @teachers = @teachers.all
    end
    # @instruments = @instruments.search_by_name(params[:query]) # render_to_stringurns teachers with coordinates
    @markers = @teachers.map do |teacher|
      {
        lat: teacher.latitude,
        lng: teacher.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { teacher: teacher }),
        image_url: helpers.asset_url('guitar-solid.svg')
      }
    end
  end


  def show
    @marker = [
      {lat: @teacher.latitude,
       lng: @teacher.longitude,
       infoWindow: render_to_string(partial: "info_window_show", locals: { teacher: @teacher }),
       image_url: helpers.asset_url('noten.png')
    }]
    @instruments = Instrument.where(user_id: params[:id])
    @genres = Genre.where(user_id: params[:id])
    @reviews = Review.where(teacher_id: params[:id])
    @availabilities = Availability.where(teacher_id: params[:id])
    @timeslots = Timeslot.where(availability_id: params[:id])
    @vouchers = Voucher.where(teacher_id: params[:id])
    @voucher = Voucher.new
  end

  # def new
  #   @teacher = Teacher.new(params)
  # end

  # def create
  #   @teacher = Teacher.new(params)
  # end

  private

  def set_teacher
    @teacher = User.find(params[:id])
  end



  # def teacher_params
  #   params.require(teacher).permit(:name
  # end
end

app/views/teachers/_info_window.html.erb
<dif class="info"><%= image_tag teacher.photo_url, class: "avatar" %>
<h2><%= teacher.first_name %></h2>
<% teacher.instruments.each do |instrument| %>
  <p><%= instrument.name.capitalize %> teacher</p>
<%end %>
<%= link_to "See Profile", teacher_path(teacher), class: "btn btn-flat-window"%></div>

app/views/teachers/_info_window_show.html.erb
<div class="info"><%= image_tag @teacher.photo_url, class: "avatar" %>

<h3><%= @teacher.first_name %> <%= @teacher.last_name %></h3>
<% @teacher.instruments.each do |instrument| %>
  <p><%= instrument.name.capitalize %></p>
<%end %>
<p><%= @teacher.address %></p></div>

app/views/teachers/index.html.erb
<div class="container">
<div class="upper-block">
<div class="search-index">
    <!-- <div class="search-form-control form-group"> -->
<div class="search-form-control form-group">
<%= form_tag teachers_path, method: :get do %>
  <%= text_field_tag :city,
    params[:city],
    placeholder: "Enter your address or postcode", class: "form-control string-required"
  %>
  </div>
<div class="search-form-control form-group">

   <%= text_field_tag :instrument,
    params[:instrument],
    placeholder: "Enter an instrument", class: "form-control string-required"
  %>
  </div>
  <%= button_tag(type: "submit", class: "btn btn-flat-search", style: "color: white;") do %>
    Search <i class="fas fa-search"></i>
<% end %>
<% end %>

  </div>

  <h2 id="h2-index" style="text-align: left">Wow, we found <%= @teachers.count%> awesome music teachers close to you! </h2>

  </div>
</div>
<div class="container d-flex">
  <div class="cards-index">
  <% @teachers.shuffle.each do |teacher| %>
    <div id="login-container">
      <%= image_tag teacher.photo_url, class: "profile-img" %>
      <h2><%= teacher.first_name%></h2>
      <% teacher.instruments.each do |instrument| %>
              <h6><%= instrument.name.capitalize %> teacher</h6>
            <%end %>
      <% teacher.genres.each do |genre| %>
              <p>Genre: <%= genre.name %></p>
            <%end %>
      <div href="#" class="cta">
      <span><%= link_to "See Profile", teacher_path(teacher)%></span>
        <svg width="10px" height="7px" viewBox="0 0 13 10">
          <path d="M1,5 L11,5"></path>
          <polyline points="8 1 12 5 8 9"></polyline>
        </svg>
      </div>
      <div class="social">
       <h5><%= teacher.price_per_hour %>€/h</h5>
      </div>
    </div>
  <% end %>
</div>
  <div class= "d-flex" id="map"
      style="width: 100%; height: 600px;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
      marker-color="$aqua">
  </div>

</div>


<script>initMapbox()</script>

app/views/teachers/show.html.erb
<div class="container">
  <div class="content">
    <div class="card-show">
        <%= image_tag @teacher.photo_url %>
      <div class="card-show-info">
        <div>
          <h2><strong><%= @teacher.first_name %> <%= @teacher.last_name %></strong></h2>
            <% @instruments.each do |instrument| %>
              <h3><%= instrument.name.capitalize %></h3>
            <%end %>
            <h5>Favorite Music:</h5>
            <% @genres.each do |genre| %>
              <p><%= genre.name %></p>
            <%end %>
          <h5>About myself:</h5>
          <p><%= @teacher.description %></p>
          <h5>Experience:</h5>
          <div class="buttom"> 
            <% @instruments.each do |instrument| %>
              <p><%= @teacher.first_name %> plays already for: <%= instrument.years_of_experience %> years!!</p>
              <p><%=  instrument.experience %></p>
            <% end %>
          </div>
          <div class="card-show-price">
            <h6><%= @teacher.price_per_hour %>€/h</h6>
          </div>
        </div>
      </div>
    </div>
      <div class="tab-wrap">

        <!-- active tab on page load gets checked attribute -->
        <input type="radio" id="tab1" name="tabGroup1" class="tab" checked>
        <label for="tab1">Availability</label>

        <input type="radio" id="tab2" name="tabGroup1" class="tab">
        <label for="tab2">Map</label>

        <input type="radio" id="tab3" name="tabGroup1" class="tab">
        <label for="tab3">Media</label>

        <input type="radio" id="tab4" name="tabGroup1" class="tab">
        <label for="tab4">Reviews</label>

        <div class="tab__content">
          <div class="content-info">
            <div class="form-wrapper", data-availabilities="<%= @availabilities.to_json %>">
              <%= simple_form_for :search, method: "get", html: { class: "form-show"} do |f| %>
                <%= f.input :starts_at, as: :string, required: false, label: false, input_html: {class: "datepicker invisible"} %>
              <% end %>
            </div>
          </div>
          <div class="book-form">
          <h5>Book lessons with <%= @teacher.first_name %> now!</h5>
          </div>
          <%= simple_form_for(:voucher, url:"/teachers/#{@teacher.id}/vouchers", method:"post") do |f| %>
          <%= hidden_field_tag "teacher_id", @teacher.id %>
            <%= f.input :counter, prompt: "Select up to 10 lessons..", collection: 1..10, label: false %>
            <%= f.submit "Book now", class: "btn btn-flat" %>
            <%= link_to "Back", teachers_path, class: "btn btn-ghost" %>
          <% end %>

        </div>

        <div class="tab__content">
          <div id="map"
            style="width: 720px; height: 508px; margin: -25px; margin-right: -60px; margin-top: -16px;"
            data-markers="<%= @marker.to_json %>"
            data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
          </div>
        </div>


        <div class="tab__content">
        <div class="video">
          <iframe width="460" height="240" src="https://www.youtube.com/embed/sTt7m96r_C4?start=12" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        </div>
        <div class="video">
          <iframe width="460" height="240" src="https://www.youtube.com/embed/pKwQlm-wldA" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        </div>
        </div>

        <div class="tab__content">
        <h4>Latest reviews:</h4>
         <% @reviews.each do |review| %>
              <div class="review-student"><p><%= review.student.first_name %> wrote:</p></div>
              <div class="review"><p><%= review.content %></p>
              </div>
          <%end %>
          <div class="review-student"><p>Maggie wrote:</p></div>
              <div class="review"><p>Thank you Eric!!! Best lesson ever!</p>
              </div>
              <div class="review-student"><p>Patrick wrote:</p></div>
              <div class="review"><p>Holly molly it works! Mister slow hand you`re a genius:)</p>
              </div>
        </div>
      </div>
  </div>

</div>



<%# <input type="text" value="#{timeslot.start_time.to_s}"> %>